apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mysql
  namespace: flux-system
spec:
  interval: 30s
  path: ./apps/mysql
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: stateful
